#define DELETE_METHOD "__gc"
#define TO_STRING_METHOD "__tostring"
#define TO_NUMBER_METHOD "__tonumber"
#define TO_BOOLEAN_METHOD "__tobolean"
#define INDEX_METHOD "__index"
#define SET_VALUE_METHOD "set_value"
#define GET_VALUE_METHOD "get_value"
#define COMMIT_METHOD "commit"
#define DESTROY_METHOD "destroy"

#define SIZE_METHOD "size"
#define GET_PATH_METHOD "get_path"

#define GET_DIR_METHOD "get_dir"
#define GET_NAME_METHOD "get_name"
#define GET_NAME_WITHOUT_EXTENSION "get_name_without_extension"
#define GET_EXTENSION_METHOD  "get_extension"
#define GET_ONLY_NAME_METHOD "get_only_name"

#define WRITE_METHOD "write"
#define REMOVE_ANY_METHOD "remove_any"
#define MOVE_ANY_METHOD "move_any"
#define COPY_ANY_METHOD "copy_any"
#define DUMP_TO_JSON_FILE_METHOD "dump_to_json_file"
#define DUMP_TO_JSON_STRING "dump_to_json_string"
#define EACH_METHOD "each"
#define MAP_METHOD "map"
#define COUNT_METHOD "count"
#define FIND_METHOD "find"
#define LIST_METHOD "list"
#define FILTER_METHOD "filter"
#define GET_SIZE_METHOD "get_size"
#define SET_EXTENSION_METHOD "set_extension"

