#define LOAD_FILE "load_file"
#define WRITE_FILE "write_file"

#define COPY_ANY_OVERWRITING "copy_any_overwriting"
#define COPY_ANY_MERGING "copy_any_merging"
#define MOVE_ANY_OVERWRITING "move_any_overwriting"
#define MOVE_ANY_MERGING "move_any_merging"
#define REMOVE_ANY "remove_any"

#define LIST_FILES "list_files"
#define LIST_FILES_RECURSIVELY "list_files_recursively"
#define LIST_DIRS "list_dirs"
#define LIST_DIRS_RECURSIVELY "list_dirs_recursively"
#define LIST_ALL "list_all"
#define LIST_ALL_RECURSIVELY "list_all_recursively"

#define BBASE_64_ENCODE_FILE "base64_encode_file"
#define BBASE_64_ENCODE "base64_encode"
#define BBASE_64_DECODE "base64_decode"

#define GENERATE_SHA "generate_sha"
#define GENERATE_SHA_FROM_FILE "generate_sha_from_file"
#define NEW_HASHER "newHasher"
#define NEW_RESOURCE "newResource"
#define IS_BLOB_FUNC "is_blob"

#define IS_DIR_FUNC "isdir"
#define IS_FILE_FUNC "isfile"
#define IS_FILE_BLOB "isfile_blob"

#define GENERATE_SHA_FROM_FOLDER_BY_CONTENT "generate_sha_from_folder_by_content"
#define GENERATE_SHA_FROM_FOLDER_BY_LAST_MODIFICATION "generate_sha_from_folder_by_last_modification"
#define CONCAT_PATH "concat_path"
#define NEW_TRANSACTION_FROM_JSON_STRING "new_transaction_from_json_string"
#define NEW_TRANSACTION_FROM_JSON_FILE "new_transaction_from_file"
#define TRY_NEW_TRANSACTION_FROM_JSON_STRING "try_new_transaction_from_string"
#define TRY_NEW_TRANSACTION_FROM_JSON_FILE "try_new_transaction_from_file"
#define NEW_TRANSACTION "newTransaction"
#define NEW_SCHEMA "newSchema"
#define NEW_PATH "newPath"
#define NEW_TREE "newTree"
#define NEW_TREE_FROM_HARWARE "newTree_from_hardware"
#define NEW_TREE_FROM_JSON_FILE "newTree_from_json_file"
#define NEW_TREE_FROM_JSON_STRING "newTree_from_json_string"
#define TRY_NEW_TREE_FROM_JSON_FILE "try_newTree_from_json_file"
#define TRY_NEW_TREE_FROM_JSON_STRING "try_newTree_from_json_string"

#define STARTS_WITH "starts_with"
#define ENDS_WITH "ends_with"
#define NEW_RANDONIZER "newRandonizer"
#define NEW_FORK "newFork"
#define NEW_LOCKER "newLocker"
#define GET_ENTITY_LAST_MODIFICATION_IN_UNIX "get_entity_last_modification_in_unix"
#define  GET_ENTITY_LAST_MODIFICATION "get_entity_last_modification"

