#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#include "dependencies/doTheWorld.c"
#include "headers/key_val.h"
#include "structs/key_val.c"
#include "sever.c"