#define CWEB_HYDRATION_DEFAULT_BODY_SIZE 5000
#define CWEB_HYDRATION_CALBACK_HANDLER_ROUTE "/private_cweb_hydration_main_callback_handler"
#define PRIVATE_CWEB_PRIVATE_STACK "private_cweb_private_stack"
